logging:
    directory: logs/
    file: logs/content-mapper-api.log
    level:
        org.springframework: INFO 
        com.bmj: DEBUG

spring:
    jpa:
        show-sql: true
        format_sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        test-on-borrow: true
        validation-query: SELECT 1;
        validation-interval: 60000
        platform: postgres
        url: jdbc:postgresql://content-postgresql-dev-201.internal.aws.bmjgroup.com/content
        username: content_user
        password: content_user
        driver-class-name: org.postgresql.Driver
    
