CREATE TABLE ELUCIDAT_CONTENT_MAPPING(
   ID           SERIAL PRIMARY KEY NOT NULL,
   MODULE_ID    INT NOT NULL,
   ELUCIDAT_ID  VARCHAR(30) NOT NULL,
   LOCALE       VARCHAR(8)  NOT NULL,
    UNIQUE (MODULE_ID, ELUCIDAT_ID, LOCALE),
    UNIQUE (MODULE_ID, LOCALE),
    UNIQUE (ELUCIDAT_ID, LOCALE),
    UNIQUE (MODULE_ID, ELUCIDAT_ID)
);
